using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace EulerLibrary.Problems
{
    public class EvenFibonacci : IEulerSolution
    {
        /// <summary>
        /// Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
        /// By starting with 1 and 2, the first 10 terms will be:
        ///     1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
        /// By considering the terms in the Fibonacci sequence whose values do not exceed four million, 
        /// find the sum of the even-valued terms.
        /// </summary>
        /// <returns></returns>
        public string Compute()
        {
            long result = 2;
            long term1 = 1;
            long term2 = 2;
            long sum;

            sum = term1 + term2;
            while (sum < 4000000)
            {
                if (MathLibrary.IsMultiple(sum, 2)) result += sum;
                term1 = term2;
                term2 = sum;
                sum = term1 + term2;
            }

            return result.ToString();
        }
    }
}
