using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace EulerLibrary.Problems
{
    /// <summary>
    /// Pentagonal numbers are generated by the formula, Pn=n(3n−1)/2. The first ten pentagonal numbers are:
    ///
    /// 1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...
    ///
    /// It can be seen that P4 + P7 = 22 + 70 = 92 = P8. However, their difference, 70 − 22 = 48, is not pentagonal.
    ///
    /// Find the pair of pentagonal numbers, Pj and Pk, for which their sum and difference are pentagonal 
    /// and D = |Pk − Pj| is minimised; what is the value of D?
    ///
    /// </summary>
    public class PentagonNumbers : IEulerSolution
    {
        public string Compute()
        {
            long result = 999999999;
            List<long> pentagonList = MathLibrary.GetPentagon(5000);
            long[] pentagonArray = pentagonList.ToArray();

            for (long pj = 0; pj < pentagonArray.Length - 1; pj++)
                for (long pk = pj + 1; pk < pentagonArray.Length; pk++)
                {
                    if (!pentagonList.Contains(pentagonArray[pj] + pentagonArray[pk])) continue;
                    if (!pentagonList.Contains(pentagonArray[pk] - pentagonArray[pj])) continue;
                    long difference = pentagonArray[pk] - pentagonArray[pj];
                    if (difference < result) result = difference;
                }

            return result.ToString();
        }
    }
}
