using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace EulerLibrary.Problems
{
    /// <summary>
    /// Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:
    ///
    /// Triangle   Tn=n(n+1)/2   1, 3, 6, 10, 15, ... 
    /// Pentagonal   Pn=n(3n−1)/2   1, 5, 12, 22, 35, ... 
    /// Hexagonal   Hn=n(2n−1)   1, 6, 15, 28, 45, ... 
    ///
    /// It can be verified that T285 = P165 = H143 = 40755.
    ///
    /// Find the next triangle number that is also pentagonal and hexagonal
    ///
    /// </summary>
    public class TriPentHex : IEulerSolution
    {
        public string Compute()
        {
            long result = 0;
            long count = 0;
            List<long> triangleNumbers = MathLibrary.GetTriangle(100000);
            List<long> pentagonNumbers = MathLibrary.GetPentagon(100000);
            List<long> hexagonNumbers = MathLibrary.GetHexagon(100000);

            foreach (long number in triangleNumbers)
            {
                count++;
                if (count <= 285) continue;
                if (!pentagonNumbers.Contains(number)) continue;
                if (!hexagonNumbers.Contains(number)) continue;
                result = number;
                break;
            }
            return result.ToString();
        }
    }
}
